[versions]
agp = "9.3.1"
kotlin = "2.4.10"
android-minSdk = "26"
android-compileSdk = "37"
android-ndk = "28.2.13676358"
jvm = "21"
lib = "1.1.4"
vanniktechMavenPublish = "0.37.0"
kotlinx-serialization = "1.11.0"
 # Corutines
kotlinx-coroutines = "1.11.0"
ktfmt = "0.27.0"

# Logging
logbackClassic = "1.6.2"
kermit = "2.1.0"

# Util
ipaddress = "5.6.2"
cryptoRand = "0.6.0"
bc = "1.85.2"
humanReadable = "1.13.1"
datetime = "0.8.0"
commonsValidator = "1.11.0"

# Android
lifecycle-runtime-compose = "2.11.0"
libsu = "6.0.0"

# Desktop
jetbrainsKotlinJvm = "2.4.10"
coreKtx = "1.19.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.8.0"
material = "1.14.0"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }

# Android
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle-runtime-compose" }
libsu = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Logging
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }

# Corutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# Util
ipaddress = { module = "com.github.seancfoley:ipaddress", version.ref = "ipaddress" }
crypto-rand = { module = "org.kotlincrypto.random:crypto-rand", version.ref = "cryptoRand" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bc" }
human-readable = { module = "nl.jacobras:Human-Readable", version.ref = "humanReadable" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
